settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: app
  path: .
  commands:
    install:
      status: true
      method: go build -o /go/bin/twitter-clone-api
      dir: app
    run:
      status: true
      method: /go/bin/twitter-clone-api
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
