version: "3"
services:
  app:
    container_name: "api"
    build: ./docker/app
    volumes:
      - .:/go/src/github.com/NasSilverBullet/twitter-clone-api
    ports:
      - "8080:8080"
    working_dir: /go/src/github.com/NasSilverBullet/twitter-clone-api
    command: sh -c "realize start --name='app' --run"
    depends_on:
      - db
  db:
    container_name: "mysql"
    build: ./docker/db
    volumes:
      - .:/go/src/github.com/NasSilverBullet/twitter-clone-api
      - mysql_db:/var/lib/mysql:delegated
    ports:
      - "3306:3306"
    working_dir: /go/src/github.com/NasSilverBullet/twitter-clone-api
    environment:
      - MYSQL_DATABASE=api
      - MYSQL_ROOT_PASSWORD=password
volumes:
  mysql_db:
    driver: local
