#!/bin/sh

load_env() {
  . ./../.env
}

up() {
  echo "start migrate up"

  mysql --host="$DB_HOST" -P "$DB_PORT" --password="$DB_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE"

  sql=`find . -print | grep migrations | grep up.sql | sort | xargs cat`

  mysql --host="$DB_HOST" -P "$DB_PORT" --password="$DB_PASSWORD" -e "USE $DB_DATABASE; $sql"

  echo "finish migrate up"
}

down() {
  echo "start migrate down"

  sql=`find . -print | grep migrations | grep down.sql | sort -r | xargs cat`

  mysql --host="$DB_HOST" -P "$DB_PORT" --password="$DB_PASSWORD" -e "USE $DB_DATABASE; $sql"

  echo "finish migrate down"
}

seed() {
  echo "start db seed"

  sql=`find . -print | grep seeds | grep .sql | sort | xargs cat`

  mysql --host="$DB_HOST" -P "$DB_PORT" --password="$DB_PASSWORD" -e "USE $DB_DATABASE; $sql"

  echo "finish db seed"
}

gen() {
  prefix=`TZ=UTC-9 date +%Y%m%d%H%M%S`
  upf="migrations/"$prefix"_create_"$1"_table.up.sql"
  downf="migrations/"$prefix"_create_"$1"_table.down.sql"
  seedf="seeds/"$1"_table.sql"

  touch $upf
  touch $downf
  touch $seedf

  echo "$upf"
  echo "$downf"
  echo "$seedf"
  echo "are generated successfully"
}

login() {
  mysql --host="$DB_HOST" -P "$DB_PORT" --password="$DB_PASSWORD" "$DB_DATABASE"
}

default() {
  echo "exit";
}

run() {
  case "$1" in
    "up" ) up ;;

    "down" ) down ;;

    "seed" ) seed ;;

    "gen" )
      if [ $# -eq 1 ]; then
        echo -n "please input table name : "
        read key
        gen $key
      fi
      if [ $# -eq 2 ]; then
        gen $2
      fi
      ;;

    "login" ) login ;;

    * ) default $1 ;;
  esac
}

###

cd `dirname $0`

load_env

if [ $# -lt 1 ]; then
  echo -n "plase select migrate mode ( up | down | seed | gen | login ) : "

  read key

  run $key

  exit 0
fi

if [ $# -ge 1 -a $# -le 2 ]; then
  run $1 $2

  exit 0
fi

echo "please set correct command"

exit 1
